### ISSUE TITLE
[FEATURE] MySQL Compatible ?

### ISSUE THREAD

**Issue by UltimateByte** [MalboroDEV/PermaProps#2]
Amazing script already btw.
But could you make it MySQL compatible ? For server admins, i'd be way better to remove props and list them all, make some adjustments and stuff.

You can see this mod for utime to get some inspiration about how to connect to an external SQL Database http://forums.ulyssesmod.net/index.php?topic=5737.0

**Comment by MalboroDEV** [comment]
Thank you !
Yes I can do this !

**Comment by UltimateByte** [comment]
Are you serious ? I mean... Your addon is one of the most useful, simple, and popular in GM, and nobody ever asked that to you ?! And you say you can do it, just as simple as that ?! It's wonderful !
BTW if you don't have a working MySQL system to test your addon, i'm of course OK to make any test you want. 

PS : Your avatar nearly gave me boner.

**Comment by MalboroDEV** [comment]
Yes it is simple ... VERY simple !

Give me your steam pls :)

Ok why not ( PS : Your avatar nearly gave me boner. ) :')

2015-05-08 14:31 GMT+02:00 UltimateByte notifications@github.com:

**Comment by UltimateByte** [comment]
That's awesome !
My Steam is the same as here : UltimateByte (mesnie.org).

PS : Sorry if that's you or your GF as your avatar, those kind of pics are too often used for trolling. :)

**Comment by AnthoDingo** [comment]
Hello, if you're still interested, I create a fork with MySQL support : https://github.com/Janus-SGN/PermaProps

**Comment by UltimateByte** [comment]
That's pretty cool dude !
Did you make any kind of migration command, to go from sv.db (sqlite) to MySQL ?

**Comment by AnthoDingo** [comment]
Unfortunately not, but you can extract the data by downloading the file and sv.db by exploring and saving with software http://sqlitebrowser.org/.

**Comment by AnthoDingo** [comment]
Hello, I write your function.
https://github.com/Janus-SGN/PermaProps/blob/master/lua/weapons/gmod_tool/stools/permaprops.lua.mysql#L659

You can now migrate from sqlite to mysql only on server side.

If some errors, open issues on my repo ;)

**Comment by MalboroDEV** [comment]
#Janus-SGN: In the next version of PP, you can choice the SQL ( Lite or MySQL ), like the DarkRP ;) You need just wait :p

**Comment by AnthoDingo** [comment]
I think yours will be better than mine ;)

**Comment by dhkatz** [comment]
Did this ever get fixed?

**Comment by UltimateByte** [comment]
Fixed ? It's a feature request.

**Comment by dhkatz** [comment]
Well I saw by looking through the code that it's there but labeled as broken.

**Comment by VaasKahnGrim** [comment]
is this working yet, its currently 2017 and doesn't look like this was closed yet so figured I'd ask if it now works with mySQL or still not working

**Comment by NercoLive** [comment]
is it added yet, its currently 2020 and it's still not closed
